// <auto-generated />
using System;
using Hoops.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hoops.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904215424_AddGames")]
    partial class AddGames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hoops.Modules.Competitions.Domain.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("RuleSet")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rule_set");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("slug");

                    b.Property<DateOnly?>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_competitions");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_competitions_season_id");

                    b.HasIndex("OrganisationId", "SeasonId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_competitions_organisation_id_season_id_slug");

                    b.ToTable("competitions", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Competitions.Domain.CompetitionTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<int?>("Seed")
                        .HasColumnType("integer")
                        .HasColumnName("seed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_competition_teams");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_competition_teams_group_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_competition_teams_team_id");

                    b.HasIndex("CompetitionId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_competition_teams_competition_id_team_id");

                    b.ToTable("competition_teams", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Competitions.Domain.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("StageId")
                        .HasDatabaseName("ix_groups_stage_id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Competitions.Domain.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_seasons");

                    b.HasIndex("OrganisationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_seasons_organisation_id_name");

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Competitions.Domain.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("StageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_stages");

                    b.HasIndex("CompetitionId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_stages_competition_id_sequence");

                    b.ToTable("stages", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Competitions.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("char(3)")
                        .HasColumnName("abbreviation");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("HomeVenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_venue_id");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PrimaryColour")
                        .HasColumnType("text")
                        .HasColumnName("primary_colour");

                    b.Property<string>("SecondaryColour")
                        .HasColumnType("text")
                        .HasColumnName("secondary_colour");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("HomeVenueId")
                        .HasDatabaseName("ix_teams_home_venue_id");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("ix_teams_organisation_id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Competitions.Domain.TeamStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_team_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_team_staff");

                    b.HasIndex("CompetitionTeamId")
                        .HasDatabaseName("ix_team_staff_competition_team_id");

                    b.ToTable("team_staff", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Competitions.Domain.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<int>("CourtCount")
                        .HasColumnType("integer")
                        .HasColumnName("court_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_venues");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("ix_venues_organisation_id");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.GameRecording.Domain.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AwayCompetitionTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("away_competition_team_id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("HomeCompetitionTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_competition_team_id");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<DateTimeOffset?>("RosterLockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("roster_locked_at");

                    b.Property<string>("RuleSetSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("rule_set_snapshot");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<Guid?>("StageId")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("AwayCompetitionTeamId")
                        .HasDatabaseName("ix_games_away_competition_team_id");

                    b.HasIndex("HomeCompetitionTeamId")
                        .HasDatabaseName("ix_games_home_competition_team_id");

                    b.HasIndex("StageId")
                        .HasDatabaseName("ix_games_stage_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_games_venue_id");

                    b.HasIndex("CompetitionId", "ScheduledAt")
                        .HasDatabaseName("ix_games_competition_id_scheduled_at");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.GameRecording.Domain.GameOfficial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_game_officials");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_game_officials_game_id");

                    b.ToTable("game_officials", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.GameRecording.Domain.GameRosterEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_team_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("boolean")
                        .HasColumnName("is_captain");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("boolean")
                        .HasColumnName("is_starter");

                    b.Property<string>("JerseyNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jersey_number");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_game_roster_entries");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_game_roster_entries_game_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_game_roster_entries_player_id");

                    b.HasIndex("GameId", "CompetitionTeamId", "JerseyNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_game_roster_entries_game_id_competition_team_id_jersey_numb");

                    b.ToTable("game_roster_entries", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Identity.Domain.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .HasColumnType("char(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultTimezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("UTC")
                        .HasColumnName("default_timezone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organisations");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organisations_slug");

                    b.ToTable("organisations", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Identity.Domain.OrganisationMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("InvitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_at");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organisation_memberships");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organisation_memberships_user_id");

                    b.HasIndex("OrganisationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_organisation_memberships_organisation_id_user_id");

                    b.ToTable("organisation_memberships", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Identity.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Identity.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsSystemAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_admin");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Registry.Domain.ConsentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CapturedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("captured_by_user_id");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consent_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EvidenceObjectKey")
                        .HasColumnType("text")
                        .HasColumnName("evidence_object_key");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("ScopeVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id")
                        .HasName("pk_consent_records");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_consent_records_player_id");

                    b.ToTable("consent_records", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Registry.Domain.MergeProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evidence");

                    b.Property<Guid>("KeepPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("keep_player_id");

                    b.Property<Guid>("MergePlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("merge_player_id");

                    b.Property<DateTimeOffset>("ProposedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proposed_at");

                    b.Property<Guid>("ProposedByOrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposed_by_organisation_id");

                    b.Property<Guid>("ProposedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_merge_proposals");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_merge_proposals_status");

                    b.ToTable("merge_proposals", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Registry.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AnonymisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anonymised_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DobEvidenceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dob_evidence_type");

                    b.Property<DateTimeOffset?>("DobVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dob_verified_at");

                    b.Property<string>("DominantHand")
                        .HasColumnType("text")
                        .HasColumnName("dominant_hand");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<Guid?>("GuardianConsentId")
                        .HasColumnType("uuid")
                        .HasColumnName("guardian_consent_id");

                    b.Property<string>("GuardianName")
                        .HasColumnType("text")
                        .HasColumnName("guardian_name");

                    b.Property<string>("GuardianPhone")
                        .HasColumnType("text")
                        .HasColumnName("guardian_phone");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("integer")
                        .HasColumnName("height_cm");

                    b.Property<string>("IdentityTier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_tier");

                    b.Property<string>("KnownAs")
                        .HasColumnType("text")
                        .HasColumnName("known_as");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("MergedIntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_into_id");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("nationality");

                    b.Property<byte[]>("NinHmac")
                        .HasColumnType("bytea")
                        .HasColumnName("nin_hmac");

                    b.Property<string>("NinVerificationProvider")
                        .HasColumnType("text")
                        .HasColumnName("nin_verification_provider");

                    b.Property<string>("NinVerificationRef")
                        .HasColumnType("text")
                        .HasColumnName("nin_verification_ref");

                    b.Property<bool>("NinVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("nin_verified");

                    b.Property<DateTimeOffset?>("NinVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("nin_verified_at");

                    b.Property<string>("PhotoObjectKey")
                        .HasColumnType("text")
                        .HasColumnName("photo_object_key");

                    b.Property<Guid>("RegisteredByOrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registered_by_organisation_id");

                    b.Property<Guid>("RegisteredByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("registered_by_user_id");

                    b.Property<string>("StateOfOrigin")
                        .HasColumnType("text")
                        .HasColumnName("state_of_origin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("MergedIntoId")
                        .HasDatabaseName("ix_players_merged_into_id");

                    b.HasIndex("NinHmac")
                        .IsUnique()
                        .HasDatabaseName("ix_players_nin_hmac")
                        .HasFilter("nin_hmac IS NOT NULL AND merged_into_id IS NULL");

                    b.HasIndex("RegisteredByOrganisationId")
                        .HasDatabaseName("ix_players_registered_by_organisation_id");

                    b.HasIndex("LastName", "DateOfBirth")
                        .HasDatabaseName("ix_players_last_name_date_of_birth");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Registry.Domain.PlayerEligibilityFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("FlagType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flag_type");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid>("RaisedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("raised_by_user_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_player_eligibility_flags");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_player_eligibility_flags_player_id")
                        .HasFilter("resolved_at IS NULL");

                    b.ToTable("player_eligibility_flags", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Registry.Domain.PlayerOrgLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("FirstLinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_linked_at");

                    b.Property<DateTimeOffset>("LastLinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_linked_at");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_player_org_links");

                    b.HasIndex("PlayerId", "OrganisationId")
                        .IsUnique()
                        .HasDatabaseName("ix_player_org_links_player_id_organisation_id");

                    b.ToTable("player_org_links", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Registry.Domain.RegistryAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("QueryTerms")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("query_terms");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer")
                        .HasColumnName("result_count");

                    b.HasKey("Id")
                        .HasName("pk_registry_audit");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_registry_audit_occurred_at");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_registry_audit_player_id");

                    b.ToTable("registry_audit", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Registry.Domain.RegistryLedgerEntry", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Sequence"));

                    b.Property<byte[]>("EntryHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("entry_hash");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entry_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<byte[]>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload_hash");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<byte[]>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("previous_hash");

                    b.HasKey("Sequence")
                        .HasName("pk_registry_ledger");

                    b.HasIndex("EntryHash")
                        .IsUnique()
                        .HasDatabaseName("ix_registry_ledger_entry_hash");

                    b.ToTable("registry_ledger", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Registry.Domain.RosterEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_team_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("boolean")
                        .HasColumnName("is_captain");

                    b.Property<string>("JerseyNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jersey_number");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VerifiedTier")
                        .HasColumnType("integer")
                        .HasColumnName("verified_tier");

                    b.HasKey("Id")
                        .HasName("pk_roster_entries");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_roster_entries_player_id");

                    b.HasIndex("CompetitionTeamId", "JerseyNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_roster_entries_competition_team_id_jersey_number")
                        .HasFilter("status <> 'Removed'");

                    b.HasIndex("CompetitionTeamId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_roster_entries_competition_team_id_player_id");

                    b.ToTable("roster_entries", (string)null);
                });

            modelBuilder.Entity("Hoops.Modules.Competitions.Domain.Competition", b =>
                {
                    b.HasOne("Hoops.Modules.Competitions.Domain.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competitions_seasons_season_id");
                });

            modelBuilder.Entity("Hoops.Modules.Competitions.Domain.CompetitionTeam", b =>
                {
                    b.HasOne("Hoops.Modules.Competitions.Domain.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_competition_teams_competitions_competition_id");

                    b.HasOne("Hoops.Modules.Competitions.Domain.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_competition_teams_groups_group_id");

                    b.HasOne("Hoops.Modules.Competitions.Domain.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competition_teams_teams_team_id");
                });

            modelBuilder.Entity("Hoops.Modules.Competitions.Domain.Group", b =>
                {
                    b.HasOne("Hoops.Modules.Competitions.Domain.Stage", null)
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_groups_stages_stage_id");
                });

            modelBuilder.Entity("Hoops.Modules.Competitions.Domain.Stage", b =>
                {
                    b.HasOne("Hoops.Modules.Competitions.Domain.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stages_competitions_competition_id");
                });

            modelBuilder.Entity("Hoops.Modules.Competitions.Domain.Team", b =>
                {
                    b.HasOne("Hoops.Modules.Competitions.Domain.Venue", null)
                        .WithMany()
                        .HasForeignKey("HomeVenueId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_teams_venues_home_venue_id");
                });

            modelBuilder.Entity("Hoops.Modules.Competitions.Domain.TeamStaff", b =>
                {
                    b.HasOne("Hoops.Modules.Competitions.Domain.CompetitionTeam", null)
                        .WithMany()
                        .HasForeignKey("CompetitionTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_staff_competition_teams_competition_team_id");
                });

            modelBuilder.Entity("Hoops.Modules.GameRecording.Domain.Game", b =>
                {
                    b.HasOne("Hoops.Modules.Competitions.Domain.CompetitionTeam", null)
                        .WithMany()
                        .HasForeignKey("AwayCompetitionTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_games_competition_teams_away_competition_team_id");

                    b.HasOne("Hoops.Modules.Competitions.Domain.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_games_competitions_competition_id");

                    b.HasOne("Hoops.Modules.Competitions.Domain.CompetitionTeam", null)
                        .WithMany()
                        .HasForeignKey("HomeCompetitionTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_games_competition_teams_home_competition_team_id");

                    b.HasOne("Hoops.Modules.Competitions.Domain.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_games_venues_venue_id");
                });

            modelBuilder.Entity("Hoops.Modules.GameRecording.Domain.GameOfficial", b =>
                {
                    b.HasOne("Hoops.Modules.GameRecording.Domain.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_officials_games_game_id");
                });

            modelBuilder.Entity("Hoops.Modules.GameRecording.Domain.GameRosterEntry", b =>
                {
                    b.HasOne("Hoops.Modules.GameRecording.Domain.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_roster_entries_games_game_id");

                    b.HasOne("Hoops.Modules.Registry.Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_game_roster_entries_players_player_id");
                });

            modelBuilder.Entity("Hoops.Modules.Identity.Domain.OrganisationMembership", b =>
                {
                    b.HasOne("Hoops.Modules.Identity.Domain.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organisation_memberships_organisations_organisation_id");

                    b.HasOne("Hoops.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organisation_memberships_users_user_id");
                });

            modelBuilder.Entity("Hoops.Modules.Identity.Domain.RefreshToken", b =>
                {
                    b.HasOne("Hoops.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("Hoops.Modules.Registry.Domain.ConsentRecord", b =>
                {
                    b.HasOne("Hoops.Modules.Registry.Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consent_records_players_player_id");
                });

            modelBuilder.Entity("Hoops.Modules.Registry.Domain.Player", b =>
                {
                    b.HasOne("Hoops.Modules.Registry.Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("MergedIntoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_players_players_merged_into_id");
                });

            modelBuilder.Entity("Hoops.Modules.Registry.Domain.PlayerEligibilityFlag", b =>
                {
                    b.HasOne("Hoops.Modules.Registry.Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_eligibility_flags_players_player_id");
                });

            modelBuilder.Entity("Hoops.Modules.Registry.Domain.PlayerOrgLink", b =>
                {
                    b.HasOne("Hoops.Modules.Registry.Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_org_links_players_player_id");
                });

            modelBuilder.Entity("Hoops.Modules.Registry.Domain.RosterEntry", b =>
                {
                    b.HasOne("Hoops.Modules.Competitions.Domain.CompetitionTeam", null)
                        .WithMany()
                        .HasForeignKey("CompetitionTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roster_entries_competition_teams_competition_team_id");

                    b.HasOne("Hoops.Modules.Registry.Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roster_entries_players_player_id");
                });
#pragma warning restore 612, 618
        }
    }
}
